framework:
    messenger:
        transports:
            async_mailer:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%/email'
              options:
                exchange:
                  name: mailer
                  type: direct

        routing:
          'App\Message\MailMessage': async_mailer
