version: '3.4'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw

  php:
    build:
      context: .
      target: app_php
    depends_on:
      - db
    volumes:
      - ./:/srv/app:rw,cached
      - ./var:/srv/app/var:rw
      - ./public:/srv/app/public

  nginx:
    build:
      context: .
      target: app_nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/app/public:rw,cached

  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  postgres-data: ~
