version: '3.4'

services:
  php:
    networks:
      messenger_network:
        ipv4_address: 182.52.154.2
  nginx:
    ports:
      - 80:80
    networks:
      messenger_network:
        ipv4_address: 182.52.154.5
  db:
    ports:
      - "5435:5432"
    networks:
      messenger_network:
        ipv4_address: 182.52.154.3

  maildev:
    image: djfarrelly/maildev:latest
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8082:80"
      - "8083:25"
    networks:
      messenger_network:
        ipv4_address: 182.52.154.4

  rabbitmq:
    restart: always
    networks:
      messenger_network:
        ipv4_address: 182.52.154.6
networks:
  messenger_network:
    ipam:
      config:
        - subnet: 182.52.154.0/24
